version: "3.9"
name: "road_vision__edge"
services:
  edge:
    container_name: edge
    build: ../
    environment:
      MQTT_BROKER_HOST: "mqtt"
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC: "agent_data_topic"
      HUB_HOST: "store"
      HUB_PORT: 8000
      HUB_MQTT_BROKER_HOST: "mqtt"
      HUB_MQTT_BROKER_PORT: 1883
      HUB_MQTT_TOPIC: "processed_data_topic"
    networks:
      mqtt_network:
      edge_hub:


networks:
  mqtt_network:
    external: true
    name: road_vision__hub_mqtt_network
  db_network:
  edge_hub:
  hub:
  hub_store:
  hub_redis:


volumes:
  postgres_data:
  pgadmin-data:
