name: "road_vision__agent"
services:
  fake_agent:
    container_name: agent
    build: ../
    environment:
      MQTT_BROKER_HOST: "mqtt"
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC: "agent_data_topic"
      DELAY: 0.1
    networks:
      mqtt_network:


networks:
  mqtt_network:
    external: true
    name: road_vision__hub_mqtt_network
